'use strict';

const http = require('node:http');

/**
 * Tiny in-process RSS 2.0 feed server used by the ingestion tests.
 *
 * It serves ONE feed, mounted at a configurable path, whose item set is
 * mutable at runtime:
 *
 *   server.addItem({ title, description })   -> adds a new item with a fresh
 *                                                guid and returns it
 *   server.updateItem(guid, { title, ... })  -> mutates an existing item
 *   server.items                             -> current item array (read-only)
 *   server.reset()                           -> clear all items
 *
 * The feed is served with Content-Type: application/rss+xml and correct RFC822
 * dates so a real RSS parser (SimplePie etc.) accepts it. Items keep a stable
 * guid so the server under test can match updates to existing articles rather
 * than treating every refresh as brand-new items.
 *
 * Reachability note: the greader SERVER must be able to reach this feed's
 * public URL, not just the test process. For a remote server, set
 * GREADER_FEED_PUBLIC_URL to an address the server can resolve.
 */
class FeedServer {
  constructor() {
    /** @type {Array<{guid:string,title:string,description:string,link:string,pubDate:Date,updated:Date}>} */
    this._items = [];
    this._seq = 0;
    this._http = null;
    this._port = 0;
  }

  get items() {
    return this._items.map((i) => ({ ...i }));
  }

  /** Add a new item. guid is generated and stable for the item's lifetime. */
  addItem({ title, description = '', link } = {}) {
    this._seq += 1;
    const now = new Date();
    const guid = `feedserver-${process.pid}-${now.getTime()}-${this._seq}`;
    const item = {
      guid,
      title: title ?? `Item ${this._seq}`,
      description: description ?? `<p>Body of item ${this._seq}</p>`,
      link: link ?? `http://feedserver.local/item/${this._seq}`,
      pubDate: now,
      updated: now,
    };
    this._items.push(item);
    return item;
  }

  /** Mutate an existing item by guid. Returns the updated item or null. */
  updateItem(guid, patch) {
    const it = this._items.find((x) => x.guid === guid);
    if (!it) return null;
    if (patch.title !== undefined) it.title = patch.title;
    if (patch.description !== undefined) it.description = patch.description;
    if (patch.link !== undefined) it.link = patch.link;
    it.updated = new Date();
    return { ...it };
  }

  reset() {
    this._items = [];
    this._seq = 0;
  }

  /** Start listening. Resolves with { port, publicUrl } once up. */
  start({ bind = '127.0.0.1:0', publicUrl = '', mountPath = '/feed.xml' } = {}) {
    const [host, portStr] = bind.split(':');
    const port = Number(portStr || 0);
    return new Promise((resolve, reject) => {
      const onErr = (e) => reject(new Error('FeedServer bind failed: ' + e.message));
      this._http = http.createServer((req, res) => this._handle(req, res, mountPath));
      this._http.once('error', onErr);
      this._http.listen(port, host, () => {
        this._http.removeListener('error', onErr);
        this._port = this._http.address().port;
        const pub = publicUrl || `http://127.0.0.1:${this._port}${mountPath}`;
        resolve({ port: this._port, publicUrl: pub, mountPath });
      });
    });
  }

  async stop() {
    if (!this._http) return;
    return new Promise((r) => this._http.close(() => { this._http = null; r(); }));
  }

  _handle(req, res, mountPath) {
    const u = new URL(req.url, 'http://x');
    if (u.pathname !== mountPath) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      return res.end('not found');
    }
    const xml = this._renderRss();
    res.writeHead(200, {
      'Content-Type': 'application/rss+xml; charset=utf-8',
      'Cache-Control': 'no-store',
    });
    res.end(xml);
  }

  _renderRss() {
    const items = this._items.map((it) => {
      const date = (d) => d.toUTCString(); // RFC 822 / RFC 1123
      return [
        '    <item>',
        `      <title>${esc(it.title)}</title>`,
        `      <description>${esc(it.description)}</description>`,
        `      <link>${esc(it.link)}</link>`,
        `      <guid isPermaLink="false">${esc(it.guid)}</guid>`,
        `      <pubDate>${date(it.pubDate)}</pubDate>`,
        '    </item>',
      ].join('\n');
    }).join('\n');

    const built = new Date().toUTCString();
    return [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<rss version="2.0">',
      '  <channel>',
      '    <title>Greader Contract Test Feed</title>',
      '    <link>http://feedserver.local/</link>',
      '    <description>Throwaway feed generated by the greader contract test suite</description>',
      `    <lastBuildDate>${built}</lastBuildDate>`,
      `    <pubDate>${built}</pubDate>`,
      items || '    <!-- no items -->',
      '  </channel>',
      '</rss>',
      '',
    ].join('\n');
  }
}

function esc(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

module.exports = { FeedServer };
